brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 重点：为了让 K8s 内的 Pod 能正确解析并路由回宿主机的 broker，这里需改为 host.docker.internal
brokerIP1 = host.docker.internal
