brokerClusterName=DledgerCluster
brokerName=RaftNode00
listenPort=30931
namesrvAddr=rmqnamesrv-cluster-1:9876;rmqnamesrv-cluster-2:9876
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
enableDLegerCommitLog=true
dLegerGroup=RaftNode00
dLegerPeers=n0-rmqbroker-n0:40911;n1-rmqbroker-n1:40911;n2-rmqbroker-n2:40911
dLegerSelfId=n2
sendMessageThreadPoolNums=16
brokerIP1=host.docker.internal
