{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .containerPort }}
          env:
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
              value: {{ $.Values.global.nacosAddr | quote }}
            - name: SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR
              value: {{ $.Values.global.nacosAddr | quote }}
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: {{ $.Values.global.redisClusterNodes | quote }}
            - name: ROCKETMQ_NAME_SERVER
              value: {{ $.Values.global.rocketmqNameServer | quote }}
            {{- if .env }}
{{ toYaml .env | indent 12 }}
            {{- end }}
{{- end }}
