version: '3.8'

services:
#  使用windows本地的mysql
#  mysql:
#    image: mysql:8.0
#    container_name: leaf-mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    restart: always

# 使用windows本地的redis
#  redis:
#    image: redis:7.0
#    container_name: leaf-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./data/redis:/data
#    restart: always

  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: leaf-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always

  mqnamesrv:
    image: apache/rocketmq:5.1.4
    container_name: leaf-mqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    restart: always

  mqbroker:
    image: apache/rocketmq:5.1.4
    container_name: leaf-mqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=mqnamesrv:9876
    command: sh mqbroker -c /home/rocketmq/conf/broker.conf
    depends_on:
      - mqnamesrv
    restart: always
    volumes:
      - ./data/rocketmq/broker/logs:/home/rocketmq/logs
      - ./data/rocketmq/broker/store:/home/rocketmq/store
      - ./conf/rocketmq/broker.conf:/home/rocketmq/conf/broker.conf

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: leaf-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:10.0.3
    container_name: leaf-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always

  loki:
    image: grafana/loki:2.9.2
    container_name: leaf-loki
    ports:
      - "3100:3100"
    restart: always

  promtail:
    image: grafana/promtail:2.9.2
    container_name: leaf-promtail
    volumes:
      - ./conf/promtail/config.yml:/etc/promtail/config.yml
      # 将宿主机的项目统一日志目录挂载到 Promtail 容器中
      - ../logs:/var/log/leaf
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: leaf-jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "9411:9411"   # Zipkin compatible API
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411 # 明确开启 Zipkin 收集器端点
    restart: always

  seata:
    image: seataio/seata-server:2.0.0
    container_name: leaf-seata
    ports:
      - "8091:8091" # Seata RPC port
      - "7091:7091" # Seata console port
    environment:
      - SEATA_IP=127.0.0.1 # 强制内机穿透 IP
    restart: always
