server:
  port: 8081

spring:
  application:
    name: leaf-service-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  config:
    import:
      - optional:nacos:leaf-service-user.yaml?refreshEnabled=true
  datasource:
    dynamic:
      primary: master # 默认写主库
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3307/leaf_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123123
        slave_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3308/leaf_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123123
  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:6371
          - 127.0.0.1:6372
          - 127.0.0.1:6373
          - 127.0.0.1:6374
          - 127.0.0.1:6375
          - 127.0.0.1:6376

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876;127.0.0.1:9877
  consumer:
    group: leaf-service-user-group

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0 # 100% 采样率，保证开发环境每条调用都被记录
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

logging:
  file:
    name: logs/${spring.application.name}/app.log

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
