server:
  port: 8080

spring:
  application:
    name: leaf-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    # 配置网关路由
    gateway:
      discovery:
        locator:
          # 开启基于服务发现的路由定位机制
          enabled: true
          # 服务名称转换为小写，因为通过服务名访问默认路径是大写
          lower-case-service-id: true
        
      routes:
        # 认证中心路由
        - id: leaf-auth-route
          uri: http://leaf-auth-svc:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        # 手动精确配置用户服务路由
        - id: leaf-service-user-route
          uri: lb://leaf-service-user
          predicates:
            - Path=/api/user/**
          filters:
            # 剥离前缀，即把 /api/user/1 转发给真实的微服务 /user/1
            - StripPrefix=1
        
        # 手动精确配置订单服务路由
        - id: leaf-service-order-route
          uri: lb://leaf-service-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
  config:
    import:
      - optional:nacos:leaf-gateway.yaml?refreshEnabled=true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://leaf-auth-svc:8083/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0 # 100% 采样率，保证开发环境每条调用都被记录
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

logging:
  file:
    name: logs/${spring.application.name}/app.log
